import type { CVContent } from "./cv.types";
import { cvRolesPl } from "./cv-roles.pl";

export const cvContentPl: CVContent = {
  name: "Wojciech Zieliński",
  title: "Full Stack Developer",
  contactTitle: "Curriculum Vitae",
  contactDetailsTitle: "Dane kontaktowe",
  summaryTitle: "Podsumowanie",
  contact: [
    {
      kind: "copy",
      label: "E-mail",
      value: "wojtekzielinski96@gmail.com",
      copyText: "wojtekzielinski96@gmail.com",
    },
    {
      kind: "copy",
      label: "Telefon",
      value: "+48 783 781 370",
      copyText: "+48783781370",
    },
    {
      kind: "copy",
      label: "Miasto",
      value: "Kraków, Polska",
      copyText: "Kraków, Polska",
    },
    {
      kind: "link",
      label: "GitHub",
      value: "github.com/wojtek960506",
      href: "https://github.com/wojtek960506",
      external: true,
    },
    {
      kind: "link",
      label: "LinkedIn",
      value: "linkedin.com/in/wojciech-zielinski-69944b159",
      href: "https://www.linkedin.com/in/wojciech-zielinski-69944b159/",
      external: true,
    },
    {
      kind: "link",
      label: "Portfolio",
      value: "devonion.com",
      href: "https://devonion.com",
      external: true,
    },
  ],
  cvFileName: "CV_WojciechZielinski_pl.pdf",
  cta: "Pobierz",
  backCta: "Wróć",
  summaryParagraphs: [
    "Wszechstronny inżynier oprogramowania z 5-letnim doświadczeniem w rozwoju backendu (Python, Node.js, MongoDB, PostgreSQL) oraz frontendu (TypeScript, React), pracujący w międzynarodowych i interdyscyplinarnych zespołach.",
    "Doświadczony w projektowaniu i wdrażaniu rozwiązań end-to-end, obejmujących backend, REST API oraz interfejsy frontendowe. Szybko uczę się nowych technologii i biorę odpowiedzialność za złożone funkcje.",
    "W projektach własnych najbardziej lubię tworzyć systemy full stack pomagające ludziom porządkować dane.",
  ],
  experienceTitle: "Doświadczenie zawodowe",
  educationTitle: "Wykształcenie",
  skillsTitle: "Umiejętności",
  interestsTitle: "Zainteresowania",
  roles: cvRolesPl,
  education: {
    title: "Inżynier, Informatyka",
    rows: [
      {
        id: "institution",
        label: "Uczelnia",
        value: "Politechnika Warszawska",
      },
      {
        id: "period",
        label: "Okres",
        value: "2016 - 2020",
      },
    ],
    bullets: [
      "Algorytmy i struktury danych, inżynieria systemów informacyjnych, bazy danych",
      "2 semestry na Czech Technical University w Pradze w ramach programu Erasmus+",
      "Praca dyplomowa: system klient-serwer do zapisywania i analizowania treningów z aplikacją mobilną",
    ],
  },
  skills: [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Python",
    "MongoDB",
    "Tailwind CSS",
    "Jest",
    "React Testing Library",
    "HTML",
    "CSS",
    "Angielski B2",
  ],
  interests: [
    "Wędrówki górskie",
    "Wspinaczka",
    "Rower i bikepacking",
    "Motocykle",
    "Muzyka i pianino",
    "Piłka nożna",
    "Formuła 1",
    "MotoGP",
    "Nauka języków obcych",
  ],
};
